databases:
  - name: mysitedb
    plan: free
    databaseName: sketchbook
    user: mysite

services:
  - type: web
    plan: free
    name: core
    runtime: python
    buildCommand: "./scripts/build_backend.sh && ./scripts/build_and_move_frontend.sh"
    startCommand: "./scripts/run_server.sh"   
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - fromGroup: sketchbook-prod-env
