databases:
  - name: mysitedb
    plan: free
    databaseName: sketchbook
    user: mysite

services:
  - type: web
    plan: free
    name: core
    runtime: python
    buildCommand: "./backend/build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"   
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
