# Generated by Django 5.1.1 on 2024-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_background_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(default='images/backgrounds/default.png', upload_to='images/backgrounds'),
        ),
    ]
