# Generated by Django 5.1.1 on 2024-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images\\avatars\\default.png', upload_to='images\\avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(default='images\\backgrounds\\default.png', upload_to='images\\backgrounds'),
        ),
    ]
